[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  command = "npm start"
  port = 3000
  publish = "public"

[[redirects]]
  from = "/api/notes"
  to = "/.netlify/functions/notes"
  status = 200

[[redirects]]
  from = "/api/notes/*"
  to = "/.netlify/functions/notes"
  status = 200

[[redirects]]
  from = "/api/working-hours"
  to = "/.netlify/functions/working-hours"
  status = 200

[[redirects]]
  from = "/api/working-hours/*"
  to = "/.netlify/functions/working-hours"
  status = 200

[[redirects]]
  from = "/display"
  to = "/display.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
